"""migration 1

Revision ID: 804e9b218dfc
Revises: 
Create Date: 2024-07-22 16:00:19.598509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '804e9b218dfc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoas',
    sa.Column('cpf', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('cpf')
    )
    op.create_index(op.f('ix_pessoas_cpf'), 'pessoas', ['cpf'], unique=False)
    op.create_index(op.f('ix_pessoas_email'), 'pessoas', ['email'], unique=True)
    op.create_index(op.f('ix_pessoas_nome'), 'pessoas', ['nome'], unique=True)
    op.create_table('funcionarios',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['pessoas.cpf'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funcionarios_id'), 'funcionarios', ['id'], unique=False)
    op.create_index(op.f('ix_funcionarios_password'), 'funcionarios', ['password'], unique=False)
    op.create_index(op.f('ix_funcionarios_username'), 'funcionarios', ['username'], unique=True)
    op.create_table('pacientes',
    sa.Column('numeroSUS', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.String(length=255), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.String(length=255), nullable=True),
    sa.Column('info', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_paciente'], ['pessoas.cpf'], ),
    sa.PrimaryKeyConstraint('numeroSUS')
    )
    op.create_index(op.f('ix_pacientes_id_paciente'), 'pacientes', ['id_paciente'], unique=False)
    op.create_index(op.f('ix_pacientes_info'), 'pacientes', ['info'], unique=True)
    op.create_index(op.f('ix_pacientes_numeroSUS'), 'pacientes', ['numeroSUS'], unique=False)
    op.create_index(op.f('ix_pacientes_sexo'), 'pacientes', ['sexo'], unique=True)
    op.create_table('consultas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=True),
    sa.Column('id_funcionario', sa.String(length=255), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('hbg', sa.Float(), nullable=True),
    sa.Column('tomaMedHipertensao', sa.String(length=255), nullable=True),
    sa.Column('praticaAtivFisica', sa.String(length=255), nullable=True),
    sa.Column('imc', sa.Float(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('historicoAcucarElevado', sa.String(length=255), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('cintura', sa.Float(), nullable=True),
    sa.Column('resultadoFindRisc', sa.String(length=255), nullable=True),
    sa.Column('frequenciaIngestaoVegetaisFrutas', sa.String(length=255), nullable=True),
    sa.Column('historicoFamiliar', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_funcionario'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.numeroSUS'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultas_id'), 'consultas', ['id'], unique=False)
    op.create_index(op.f('ix_consultas_id_funcionario'), 'consultas', ['id_funcionario'], unique=False)
    op.create_index(op.f('ix_consultas_id_paciente'), 'consultas', ['id_paciente'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consultas_id_paciente'), table_name='consultas')
    op.drop_index(op.f('ix_consultas_id_funcionario'), table_name='consultas')
    op.drop_index(op.f('ix_consultas_id'), table_name='consultas')
    op.drop_table('consultas')
    op.drop_index(op.f('ix_pacientes_sexo'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_numeroSUS'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_info'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_id_paciente'), table_name='pacientes')
    op.drop_table('pacientes')
    op.drop_index(op.f('ix_funcionarios_username'), table_name='funcionarios')
    op.drop_index(op.f('ix_funcionarios_password'), table_name='funcionarios')
    op.drop_index(op.f('ix_funcionarios_id'), table_name='funcionarios')
    op.drop_table('funcionarios')
    op.drop_index(op.f('ix_pessoas_nome'), table_name='pessoas')
    op.drop_index(op.f('ix_pessoas_email'), table_name='pessoas')
    op.drop_index(op.f('ix_pessoas_cpf'), table_name='pessoas')
    op.drop_table('pessoas')
    # ### end Alembic commands ###
