"""migration 2

Revision ID: 103a448cdcaf
Revises: 742d14db1066
Create Date: 2024-08-21 10:39:18.962262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '103a448cdcaf'
down_revision: Union[str, None] = '742d14db1066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pacientes_info', table_name='pacientes')
    op.create_index(op.f('ix_pacientes_info'), 'pacientes', ['info'], unique=False)
    op.drop_index('ix_pacientes_sexo', table_name='pacientes')
    op.create_index(op.f('ix_pacientes_sexo'), 'pacientes', ['sexo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pacientes_sexo'), table_name='pacientes')
    op.create_index('ix_pacientes_sexo', 'pacientes', ['sexo'], unique=True)
    op.drop_index(op.f('ix_pacientes_info'), table_name='pacientes')
    op.create_index('ix_pacientes_info', 'pacientes', ['info'], unique=True)
    # ### end Alembic commands ###
